### ISSUE TITLE
Dedication style

### ISSUE THREAD

**Issue by weijia-cheng** [richardjs/lord-dunsany_the-king-of-elflands-daughter#2]
- [x] The dedication needs the base CSS from [7.3.2](https://standardebooks.org/manual/1.6.2/7-high-level-structural-patterns)
- [x] Rather than having the actual text be in all caps, I think the dedication text should be capitalized as "To Lady Dunsany" and styled with small-caps. You can add the property `font-variant: small-caps;` to the `section[epub|type~="dedication"]` selector from 7.3.2.

**Comment by richardjs** [comment]
OK, this should be done. Thanks!
