### ISSUE TITLE
Preface signature style

### ISSUE THREAD

**Issue by weijia-cheng** [richardjs/lord-dunsany_the-king-of-elflands-daughter#4]
The signature CSS is standardized in [7.7.3.4](https://standardebooks.org/manual/1.6.2/7-high-level-structural-patterns#7.7.3.4). You should also replace the custom `#preface footer` rule with the standard footer ruler in [7.7.3.2](https://standardebooks.org/manual/1.6.2/7-high-level-structural-patterns#7.7.3.2).

**Comment by richardjs** [comment]
OK, I've modified local.css. Thanks!
