### ISSUE TITLE
Colophon semantics

### ISSUE THREAD

**Issue by weijia-cheng** [richardjs/lord-dunsany_the-king-of-elflands-daughter#5]
- [x] Personal names without links in the colophon (e.g. `<b class="name">Greg Weeks</b>`) should have the semantics `<b epub:type="z3998:personal-name">` instead.
- [x] You should remove the `time` class from `<abbr class="time eoc">a.m.</abbr>`, because that comes from an old colophon template from when you started the project that is no longer applicable.

**Comment by richardjs** [comment]
OK, done! Thanks!

**Comment by weijia-cheng** [comment]
It looks like you are still using `class` for the names but it should be `epub:type`.

**Comment by richardjs** [comment]
Oops, sorry for the oversight. Should be fixed now.
